apiVersion: v2
name: precision-viticulture-platform
description: A Helm chart for deploying the Precision Viticulture Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 20.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled